# Generated by Django 6.0.3 on 2026-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_favorite_and_alter_song_gen_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
