# Generated by Django 6.0.3 on 2026-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
