# Generated by Django 6.0.3 on 2026-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genform',
            name='voice',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('instrumental', 'Instrumental')], max_length=20),
        ),
    ]
